version: 3

includes:
  docker: ./docker

tasks:
  build:taskfiles-runner:
    cmd:
      task: docker:build
      vars:
        PROXY: '{{.PROXY | default "http://127.0.0.1:7890"}}'
        TAG: '{{printf "%s:%s" "ssuf1998/taskfiles-runner" (now | unixEpoch)}}'
