version: 3

tasks:
  build:
    vars:
      # FILE:
      # PROXY:
      # TAG:
      DIR: "{{.DIR | default .USER_WORKING_DIR}}"

    dir: "{{.DIR}}"

    cmd: |
      cmd="docker build ."
      if [ ! -z "{{.FILE}}" ]; then
        cmd="$cmd --file {{.FILE}}"
      fi
      if [ ! -z "{{.PROXY}}" ]; then
        cmd="$cmd --network host --build-arg HTTP_PROXY={{.PROXY}} --build-arg HTTPS_PROXY={{.PROXY}}"
      fi
      if [ ! -z "{{.TAG}}" ]; then
        cmd="$cmd --tag {{.TAG}}"
      fi
      eval "$cmd"

    preconditions:
      - command -v docker

  build:pocketbase:
    cmd:
      task: build
      vars:
        TAG: '{{printf "%s:%s" "ssuf1998/pocketbase" (now | unixEpoch)}}'
        DIR: ./pocketbase
