version: 3

silent: true

tasks:
  default:
    desc: "Clone a remote repository through Git over Http."

    dir: "{{.DIR}}"

    vars:
      # OWNER:
      # REPOSITORY:
      # TOKEN:
      PROVIDER: '{{default "github.com" .PROVIDER}}'
      BRANCH: '{{default "main" .BRANCH}}'
      # DEPTH:
      # IGNORE_ERROR:
      # INSCURE:
      DIR:
        sh: echo $(realpath "{{.DIR | default .USER_WORKING_DIR}}")

    requires:
      vars:
        - OWNER
        - REPOSITORY

    preconditions:
      - command -v git

    cmd: |
      url="https://{{if .TOKEN}}{{.TOKEN}}@{{end}}{{.PROVIDER}}/{{.OWNER}}/{{.REPOSITORY}}.git"
      cmd="git clone --quiet --branch {{.BRANCH}}"
      if [ ! -z "{{.INSCURE}}" ]; then
        cmd="GIT_SSL_NO_VERIFY=true $cmd"
      fi
      if [ ! -z "{{.DEPTH}}" ]; then
        cmd="$cmd --depth={{.DEPTH}}"
      fi
      if [ -z "{{.IGNORE_ERROR}}" ]; then
        eval "$cmd $url"
      else
        eval "$cmd $url" || true
      fi

  batch:
    desc: "Clone remote repositories through Git over Http."

    vars:
      {}
      # REPOSITORIES:

    requires:
      vars:
        - REPOSITORIES

    cmd:
      for: { var: REPOSITORIES, split: "," }
      vars:
        REPOSITORY: "{{.ITEM}}"
        TOKEN: { ref: .TOKEN }
        PROVIDER: { ref: .PROVIDER }
        BRANCH: { ref: .BRANCH }
        DEPTH: { ref: .DEPTH }
        IGNORE_ERROR: { ref: .IGNORE_ERROR }
        INSCURE: { ref: .INSCURE }
        DIR: { ref: .DIR }
      task: default
